### ISSUE TITLE
Fix footer relative to the content of the page

### ISSUE THREAD

**Issue by lorenahq** [etf-validator/etf-webapp#113]
Since there is already a lot of scrolling to perform when selecting the relevant tests, especially when expanding the details of them, could the footer be always located relative to the end of the content? 

Currently, as soon as you click somewhere on the page depending on where you are located both the header and footer disappear/appear. Could this behavior be disabled?

There are situations where the text remains partially hidden by the footer:
![footerhidingcontent](https://user-images.githubusercontent.com/18305657/27580725-dfc95884-5b2b-11e7-99d9-90197f39c41c.png)

(Using Google Chrome Version 59.0.3071.104 )

**Comment by jonherrmann** [comment]
> could the footer be always located relative to the end of the content?

In this installation only a contact button is shown, but you can also configure the validator to show privacy and disclaimer information. These information should be shown without scrolling. 

Thanks for the feedback, Lorena. We will discuss this internally and will get back to you, here.

**Comment by jonherrmann** [comment]
> It is agreed again that project-specific UIs should be released separately, since they do not really belong to the ETF.

see [18th SG meeting](https://github.com/etf-validator/governance/blob/master/Meetings/SG/20191217.md#governance-of-the-webapp)
