### ISSUE TITLE
View Services ETS & etf-sui-owsgtl 2.0.0-SNAPSHOT API

### ISSUE THREAD

**Issue by PaulaRodrigo-Geograma** [etf-validator/etf-webapp#149]
**Please note:

This repository is intended for issue reports specific to the ETF validator.
If you have an issue with an Executable Test Suite, then please use the
corresponding repository, for instance the [INSPIRE ETS repository](https://github.com/inspire-eu-validation/ets-repository)
if you have an issue with an INSPIRE test.

Our User, Administrator and Developer
manuals are available here: http://docs.etf-validator.net/.**

### Prerequisites for a bug report

* [x] Set a clear and descriptive title
* [x] Can you reproduce the problem
* [x] Did you [use the Github issue search](https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Ainteractive-instruments) to check whether your bug has already been reported?
* [x] Upload excerpts of the etf.log, catalina.out/log and localhost-<date>.log files. Important parts are:
the initialization log entries beginning with the ETF ASCII logo and ending with "TestRunController initialized!" plus the last exception messages.
* [x] If the problem is related to the Web user interface: include screenshots
* [x] If the problem is related to specific test data, provide the URL of your
service / the file you have uploaded or referenced.
If your service is protected or you have confidential data that you cannot
upload here, you can request an email address to which you can send URLs / files.
Please note that issues cannot be fixed for services/datasets that we cannot
access.
* [x] Don't forget to remove sensitive information from uploaded files!!!

### Description

In my company we are developing the executable tests for the view services on SOAP UI. We develop the different testCase using assertion objects type="_GroovyScriptAssertion_" and expressions based on the api: **etf-sui-owsgtl 2.0.0-SNAPSHOT API**

_http://interactive-instruments.github.io/etf-sui-ae/groovydoc/index.html?overview-summary.html_

We find limitations on its use with this new type of services. For example:

- There is no namespace defined for the view service. If there is one for download services:
_static java.lang.Object INSPIRE_DS_NS
Standard namespaces used in INSPIRE download services_

This and other problems that we have been encountering, will they be able to be solved in the near future? Do we have to update the API in order to work on the View Services?

### Operating systems and browser

- If the issue occurs in the user interface: add information about the Client operating system, the Browser name and version
- Otherwise add the etf.log and tomcat log files. If you can't: add information about the operating system on which the ETF web application is running and information about the web application server

### Steps to Reproduce

[Describe the exact steps which can be used to reproduce the problem]

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [Which behavior you expected to see instead and why.]

**Actual behavior:** [Describe the behavior you observed after following the steps]

**Comment by jonherrmann** [comment]
> This and other problems that we have been encountering, will they be able to be solved in the near future?
What kind of 'other problems' do you mean?

The missing namespaces are no bug in the library, they are only part of a missing feature that can be added by any contributor.  You can either define you own map of namespaces in each Assertion you write (note that the last parameter of the Assert groovy class constructor accepts a map of namespaces) or you can contribute to the etf-sui-owsgtl library a map of INPSIRE View Service namespace (INSPIRE_VS_NS).

**Comment by PaulaRodrigo-Geograma** [comment]
1. We also find limitations when working with the only one that refers to one of the types of View Services:
**de.interactive_instruments.xtf.wms**

Only one class "_Layer_" is defined and no description of its methods or properties is specified.

2. We miss other classes, already implemented for the services of type Download Service, that we need to implement in our development, such as:

Classes:
_Capabilities
PropertyType
MapType_

3. We also miss the implementation of the class:
¿**de.interactive_instruments.xtf.wmts**?

What would be the procedure for a collaborator to contribute this information to this API?

Thanks for all your clarifications

**Comment by jonherrmann** [comment]
> What would be the procedure for a collaborator to contribute this information to this API?

The exact procedure needs to be discussed and agreed in the future ETF steering group. The first meeting will be tomorrow 20.04.2018. It is very likely that all ETF repositories will be moved to the [ETF validator organisation](https://github.com/etf-validator) within the next week.

Until further plans and resolutions on the contribution have been taken, you could just fork the etf-sui-ae repository, implement your changes and later create a pull request.

**Comment by PaulaRodrigo-Geograma** [comment]
Where is the API etf-sui-owsgtl 2.0.0-SNAPSHOT API referenced?
You can no longer access the page http://interactive-instruments.github.io

**Comment by PaulaRodrigo-Geograma** [comment]
We have made an analysis of the classes needed in order to develop the WMS ETS.

We have found only one class "Layer" in the package of.interactive_instruments.xtf.wms. However, no description nor methods or properties are specified.

We specified the missing classes detected in de.interactive_instruments.xtf.wms to achieve the necessary developments for validations with the view services:

- GetMapRequest
- GetCapabilitiesRequest
- Service
- ContactInformation
- ContactAddress
- Capability
- CapabilityRequest
- CapabilityException
- CapabilityLayer
- EX_GeographicBoundingBox
- BoundingBox
- Layer
- Style
- LegendURL

There is importance to notice that the work is still under study.

**Comment by jonherrmann** [comment]
Closing this in favour of [EIP #36 ](https://github.com/etf-validator/governance/issues/36)
