### ISSUE TITLE
Testing dependencies

### ISSUE THREAD

**Issue by manmorjim** [etf-validator/etf-webapp#157]
There are some unit and integration tests [in the Gradle build](https://github.com/etf-validator/etf-webapp/blob/65eafd0691da491e4bd9691e8b3a8f6e864fa6be/build.gradle#L166) file hosted on Interactive Instruments repository and it would be useful to have information about them: what functions are being tested? what are the test cases? where is the source code?

**Comment by jonherrmann** [comment]
I missed to move the repository from our organisation to etf-validator org. The source code can be found [here](https://github.com/etf-validator/etf-unittest). It does not contain any tests but some objects that are used for testing in other components.

**Comment by manmorjim** [comment]
Nice! Thank you.
