### ISSUE TITLE
Cancel Start Test Run Error.

### ISSUE THREAD

**Issue by jlgarciasanchez** [etf-validator/etf-webapp#162]
### Background and Motivation:

When you close the "Configure Test Run" window, the app is redirected to base_url/#start-tests. And this page does not exist.

### Proposed change

The app should be redirected to base_url/etf-webapp/#start-tests.

### Alternatives

Configure properly the back page parameter.

### Funding

N/A

**Comment by cportele** [comment]
This behaviour may also have to do with the deployment configuration at JRC?  The "etf-webapp" path should be part of the base URL of the validator.

In other ETF deployments you are directed to the start-tests page as expected. The page that opens the dialog is http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/#start-tests, so the Cancel button of the "Configure Test Run" dialog should send you to that page.

**Comment by carlospzurita** [comment]
Related to https://github.com/inspire-eu-validation/community/issues/13

**Comment by carlospzurita** [comment]
A fix for this bug is ready on guadaltel/etf-webapp@9aa440e. A pull request will be created for this issue to be merged on https://github.com/etf-validator/etf-webapp, after its corresponding review.

**Comment by cportele** [comment]
Please create pull requests for reviews. Pull requests are meant to be reviewed and discussed, not commits. Thanks.

**Comment by jonherrmann** [comment]
Fixed in [Version 2.1 ](https://github.com/etf-validator/etf-webapp/releases/tag/2.1.0)
