### ISSUE TITLE
Error executing test suite (wfs20-1.26)

### ISSUE THREAD

**Issue by OscarD31** [etf-validator/etf-webapp#163]
Good morning!

I have deployed in my system the last etf-version I have found here: https://github.com/etf-validator/etf-webapp/releases/tag/2.0.0-rc.4

I want to test a WFS service in my development environment, so that service is not visible outside my network.

In every run, I get the following error: **Error executing test suite (wfs20-1.26)**

Looking for that error, I have found an issue about the CRS not being supported, but I thought that was weird in my case. Thanks to that issue, I have discovered that the ETF validator calls the OGC Team Engine validator (which I should have known, because it is clearly explained in the description). Obviously, that second validator can't access my service and that error is returned.

Is there a way to test WFS services without exposing them to the outside world? I haven't found a way to deploy locally the Team Engine validator. And, in any case, in the ETF config there is not a parameter to point to the locally deployed one (or at least I haven't seen it).

Thanks!!

**Comment by cportele** [comment]
1. You can deploy the Team Engine locally. See http://opengeospatial.github.io/teamengine/installation.html.

2. Currently the set up only supports the CITE deployment and we have only tested the CITE deployment so far. See [the documentation](http://docs.etf-validator.net/v2.0/Developer_manuals/Developing_Executable_Test_Suites.html#_team_engine_test_suites_supported_by_etf). However, looking at the code you should be able to change the base URL of the Team Engine deployment using the property `etf.testdrivers.teamengine.url` (see [TeTestDriver.java](https://github.com/etf-validator/etf-tetd/blob/master/src/main/java/de/interactive_instruments/etf/testdriver/te/TeTestDriver.java)).

**Comment by jonherrmann** [comment]
Related to https://github.com/etf-validator/etf-webapp/issues/223

Fixed in [Version 2.1 ](https://github.com/etf-validator/etf-webapp/releases/tag/2.1.0)
