### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by p1d1d1** [etf-validator/etf-webapp#164]
gradlew build war fails with the following error:

* Where:
Script '/home/user/Downloads/etf-webapp-master/build/gradle/ii-bda.gradle' line: 250

* What went wrong:
A problem occurred evaluating script. > repository not found: /home/user/Downloads/etf-webapp-master

**Comment by jonherrmann** [comment]
Please use [this](http://docs.etf-validator.net/v2.0/Developer_manuals/Building.html) documentation and checkout the next branch.

Todo:
- [ ] The [readme](https://github.com/etf-validator/etf-webapp#build-information) is not up-to-date and must refer to  the _Building ETF_ manual

**Comment by p1d1d1** [comment]
Ok, but I only get WFS 2.0 Conformance Test Suite

**Comment by jonherrmann** [comment]
You can find information about the ETS installation in this [section](http://docs.etf-validator.net/v2.0/Admin_manuals/index.html#ets-installation). This [section](http://docs.etf-validator.net/v2.0/Admin_manuals/index.html#_etf_configuration) may also be interesting.

**Comment by p1d1d1** [comment]
Many thanks for the support. it works like a charm :-)
