### ISSUE TITLE
Unable to reach build.gradle dependencies

### ISSUE THREAD

**Issue by carlospzurita** [etf-validator/etf-webapp#165]
### Description

When building the project using gradle, the script can't reach the artifact repository, and throws a Status Code 500

### Operating systems and browser

Ubuntu 16.04

### Steps to Reproduce

1. clone etf-webapp/next
2. go to etf-webapp folder
3. execute ./gradlew build

**Expected behavior:** Succesfully built war

**Actual behavior:**  
```Where:
Build file '/workspace/pruebaETF/build.gradle' line: 28

* What went wrong:
A problem occurred evaluating root project 'etf-webapp'.
> Could not resolve all dependencies for configuration ':classpath'.
> Could not resolve de.interactive_instruments.bda:etf-bda:[1.0.26,1.0.99].
Required by:
project :
> Could not resolve de.interactive_instruments.bda:etf-bda:[1.0.26,1.0.99].
> Failed to list versions for de.interactive_instruments.bda:etf-bda.
> Unable to load Maven meta-data from http://services.interactive-instruments.de/etfdev-af/plugins-releases-local/de/interactive_instruments/bda/etf-bda/maven-metadata.xml.
> Could not GET 'http://services.interactive-instruments.de/etfdev-af/plugins-releases-local/de/interactive_instruments/bda/etf-bda/maven-metadata.xml'. Received status code 500 from server: Internal Server Error```

**Comment by jonherrmann** [comment]
Thanks for the report, Carlos. It looks like we have an internal error with the repository (service always returns HTTP 500 status code). I'll look into it.

**Comment by carlospzurita** [comment]
We are able to get the dependencies again. Thank you very much.
