### ISSUE TITLE
Upload Failure by local installation of ETF-Validator

### ISSUE THREAD

**Issue by stbach** [etf-validator/etf-webapp#166]
As we installed a local installation of the ETF Validator as explained on http://docs.etf-validator.net/v2.0/Admin_manuals/index.html#_installation_on_windows for executing ETF Test classes we got failures regardless of the used test class - ETF Validator and neccesary software already installed as mentioned in the URL.

Failure 1: data source (xml metadata) can not be uploaded through "file upload";
2018-07-11 07:58:43.145 [http-nio-8080-exec-6] ERROR d.i.e.w.d.ApiError - EXID-1531288723145: An exception occurred while trying to invoke "http://localhost:8080/etf-webapp/v2/TestObjects"org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is de.interactive_instruments.etf.webapp.controller.LocalizableApiError

Failure 2: data source (xml metadata) can not be uploaded through "URL";
2018-07-11 08:01:32.591 [http-nio-8080-exec-3] ERROR d.i.e.w.d.ApiError - EXID-1531288892589: An exception occurred while trying to invoke "http://localhost:8080/etf-webapp/v2/TestRuns"org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is de.interactive_instruments.etf.webapp.controller.LocalizableApiError

Is this a known behaviour, maybe already fixed?

[Failure_2018-07-11 ETF_Upload.txt](https://github.com/etf-validator/etf-webapp/files/2222750/Failure_2018-07-11.ETF_Upload.txt)
[Failure_2018-07-11 ETF_URL.txt](https://github.com/etf-validator/etf-webapp/files/2222755/Failure_2018-07-11.ETF_URL.txt)
xml metadata: 
[MDzuGD_INSPIRE_BW_Verwaltungseinheiten_ATKIS_Basis-DLM_advANDinspire.xml.zip](https://github.com/etf-validator/etf-webapp/files/2222876/MDzuGD_INSPIRE_BW_Verwaltungseinheiten_ATKIS_Basis-DLM_advANDinspire.xml.zip)

**Comment by jonherrmann** [comment]
Did the web interface (or REST interface if you have automated the tests) not provide any error message?

Please also post the output of http://localhost:8080/etf-webapp/v2/status .

**Comment by DeordD** [comment]
Hi,

1. Did the web interface (or REST interface if you have automated the tests) not provide any error message?

Yes, see attachments.

 Failure 1: data source (xml metadata) can not be uploaded through "file upload";

      02_DataUpload_EN_180724.jpg

 Failure 2: data source (xml metadata) can not be uploaded through "URL";

      01_RemoteFile(URL)_EN_180724.jpg

2. Please also post the output of http://localhost:8080/etf-webapp/v2/status .

{"name":"ETF","status":"MAJOR","heartbeat":"1532425404699","willExpireAt":"1532425444699","version":"2.0.0-b180115T1110","uptime":"1123","allocatedMemory":"205367904","presumableFreeMemory":"54154656","totalSpace":"999887466496","freeSpace":"905858609152","cpuLoad":"0,000585","messages":["Less then 512 MB RAM available"]}

**Comment by jonherrmann** [comment]
Thanks for the screenshots and details. Ok, one important point is missing in the documentation:

You need to set or increase the `-Xmx` [parameter](https://docs.oracle.com/cd/E13150_01/jrockit_jvm/jrockit/jrdocs/refman/optionX.html#wp999528) in the Tomcat configuration. [This](https://cloud.githubusercontent.com/assets/13570741/24648926/97582bd6-1925-11e7-966c-a18337c56756.png) screenshot shows this for the Tomcat service configuration window (-Xmx31G to reserve 31 GB memory). You need to set this parameter to at least 4 GB ram -> `-Xmx4G` ( > 8GB are recommended).

**Comment by DeordD** [comment]
Thanks for extremely quick reply. 

Your hint has helped me to solve the problem. 
I also had to set up -Xmx4095m parameter for windows user because the default value on my machine was 512MB.  

Solution: 
1. Java Runtime Environment - Settings für Java 1.8

Runtime-Parameter: -Xmx4095m
![grafik](https://user-images.githubusercontent.com/38787131/43141512-5cf858be-8f56-11e8-9465-fc81ecec0441.png)

2. Increase -Xmx parameter in the Tomcat configuration

https://cloud.githubusercontent.com/assets/13570741/24648926/97582bd6-1925-11e7-966c-a18337c56756.png

This is done for Tomcat installation as service. 

Remark: I think that the same procedure has to be done if Tomcat is started on Windows on the console via the batch.

**Comment by jonherrmann** [comment]
closing in favour of https://github.com/etf-validator/etf-webapp/issues/167
