### ISSUE TITLE
TEAM Engine - WMS Test Suites

### ISSUE THREAD

**Issue by PaulaRodrigo-Geograma** [etf-validator/etf-webapp#170]
**Please note:

This repository is intended for issue reports specific to the ETF validator.
If you have an issue with an Executable Test Suite, then please use the
corresponding repository, for instance the [INSPIRE ETS repository](https://github.com/inspire-eu-validation/ets-repository)
if you have an issue with an INSPIRE test.

Our User, Administrator and Developer
manuals are available here: http://docs.etf-validator.net/.**

### Prerequisites for a bug report

* [x] Set a clear and descriptive title
* [x] Can you reproduce the problem
* [x] Did you [use the Github issue search](https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Ainteractive-instruments) to check whether your bug has already been reported?
* [ ] Upload excerpts of the etf.log, catalina.out/log and localhost-<date>.log files. Important parts are:
the initialization log entries beginning with the ETF ASCII logo and ending with "TestRunController initialized!" plus the last exception messages.
* [x] If the problem is related to the Web user interface: include screenshots
* [x] If the problem is related to specific test data, provide the URL of your
service / the file you have uploaded or referenced.
If your service is protected or you have confidential data that you cannot
upload here, you can request an email address to which you can send URLs / files.
Please note that issues cannot be fixed for services/datasets that we cannot
access.
* [ ] Don't forget to remove sensitive information from uploaded files!!!

### Description

We want to include other OGC tests in the ETF Inspirational Validator and we do not know where to find the references (dependencies) to the Team Engine Suist tests, could I get help?

Currently the validator adds test for WFS 2.0 adding the dependencies:

con:property
con:nameetf.supported.test.object.type.ids</con:name>
con:valueEID9981e87e-d642-43b3-ad5f-e77469075e74</con:value>
</con:property>
con:property
con:nameetf.dependency.ids</con:name>
con:valueEID95a1b6fc-2b55-3d43-9502-</con:value>
</con:property>

Where can we find these identifiers (ids) in the case of WMS, or WMTS?

thanks!

**Comment by jonherrmann** [comment]
Fully automated testing of WM and WMT services are not supported by the OGC Team Engine. There are tests but most of them require user interaction and are more like asking "do you see a web map with a street and blue lake" that need to be answered by a tester. In addition, there is no interface that ETF could use.

For that reason there are no tests / IDs you can reference in ETF.

**Comment by PaulaRodrigo-Geograma** [comment]
Thanks Jon!

Could it be integrated with the tests for SOS Services 2.0? Although they have not published any rest service to refer to from an executable test:
http://cite.opengeospatial.org/teamengine/rest/suites

**Comment by jonherrmann** [comment]
This is not possible without any rest interface.
