### ISSUE TITLE
Problem with the startup of the ETF webapp

### ISSUE THREAD

**Issue by df-git** [etf-validator/etf-webapp#175]
We are experiencing problem with the ETF webapp. We noticed that it was down; we tryed to restart it but nothing changes; the webapp is not able to start up due to some errors.
The recurring erroro is:
`[ERROR d.i.e.d.d.b.BsxDataStorage - Query Exception: SAXParseException: cvc-id.2: There are multiple occurrences of ID value 'EID95a1b6fc-2b55-3d43-9502-3b8b605bda10'.]`

I also attach the detailed log after the Tomcat's restart.
[etf.log](https://github.com/etf-validator/etf-webapp/files/2611118/etf.log)
Can you please have a look at the logs?

Thank you in advance.

**Comment by carlospzurita** [comment]
Hi @df-git 
Could you please, provide the branch of the ETS repository that you are using? This seems to be a problem with the ETS file.
Regards

**Comment by carlospzurita** [comment]
@df-git 
Could you provide us with the /etf folder, where you have all the source files to deploy the application? We can use them to compare with our own deployment to check any differences.
Regards

**Comment by df-git** [comment]
The ETF Validator is under Tomcat (/opt/tomcat-latest/webapps/etf-webapp/).
If you want we can also provide a TAR of the deployed files.

**Comment by carlospzurita** [comment]
Yes, a TAR would be very useful.

**Comment by df-git** [comment]
Sorry, I forgot the attachment.

**Comment by carlospzurita** [comment]
The ETS repository seems fine. ¿Can you check how many files on the `/home/tomcat/.etf/ds/obj` folder have the identifier **ExecutableTestSuite-EID95a1b6fc-2b55-3d43-9502-3b8b605bda10.xml**? There may be some duplicated files in that folder.

**Comment by df-git** [comment]
Thank you for the check. I checked the folder and there is only one file with the ID EID95a1b6fc-2b55-3d43-9502-3b8b605bda10

**Comment by carlospzurita** [comment]
We are going to try to reproduce the exact environment as yours. ¿Can you please provide us with the deployed .war, and the `/home/tomcat/.etf` whole folder compressed? Also, pleas tell us what branch from https://github.com/etf-validator/etf-webapp repository are using to build the .war file. That way we can deploy the application in our premises, and take a more detailed look.

**Comment by df-git** [comment]
The issue has now been solved. The process is described below:

- The last folder saved in .etf/ds/db/data/ was on the 22nd of November
- We removed the folder of the last 10 days
- We restarted the etf-webapp
- It took almost 1 hour to restart (DB creation) - A portion of startup logs are available below:

```
2018-11-28 11:31:47.746 [localhost-startStop-1] WARN  d.i.e.d.d.b.BsxDataStorage - Opening of the data storage failed, recreating it
2018-11-28 11:31:47.746 [localhost-startStop-1] WARN  d.i.e.d.d.b.BsxDataStorage - Preparing data storage reset
2018-11-28 12:26:52.103 [localhost-startStop-1] INFO  d.i.e.d.d.b.BsxDataStorage - 29478 data files added
2018-11-28 12:26:52.143 [localhost-startStop-1] INFO  d.i.e.d.d.b.BsxDataStorage - Optimizing etf-ds
2018-11-28 12:27:29.399 [localhost-startStop-1] INFO  d.i.e.d.d.b.BsxDataStorage - Recreated data storage in: 55min 41sec
2018-11-28 12:27:29.413 [localhost-startStop-1] INFO  d.i.e.d.d.b.BsxDataStorage - Database Properties
```
