### ISSUE TITLE
Upload fails for XML documents: test object could not be determined

### ISSUE THREAD

**Issue by thijsbrentjens** [etf-validator/etf-webapp#180]
### Prerequisites for a bug report

* [x] Set a clear and descriptive title
* [x] Can you reproduce the problem
* [x] Did you [use the Github issue search](https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aetf-validator) to check whether your bug has already been reported?
* [x] Upload excerpts of the etf.log, catalina.out/log and localhost-<date>.log files. Important parts are:
the initialization log entries beginning with the ETF ASCII logo and ending with "TestRunController initialized!" plus the last exception messages. 
[etf_log_uploadfailes.txt](https://github.com/etf-validator/etf-webapp/files/2638660/etf_log_uploadfailes.txt)

* [x] If the problem is related to specific test data, provide the URL of your
service / the file you have uploaded or referenced. 
[20160128_voorbeeldbestand_mtb_Amersfoort_StUF_registratief_GeoBOR.xml.txt](https://github.com/etf-validator/etf-webapp/files/2638663/20160128_voorbeeldbestand_mtb_Amersfoort_StUF_registratief_GeoBOR.xml.txt)

If your service is protected or you have confidential data that you cannot
upload here, you can request an email address to which you can send URLs / files.
Please note that issues cannot be fixed for services/datasets that we cannot
access.
* [x] Don't forget to remove sensitive information from uploaded files!!!

### Description

On our (beta) instance of the ETF validator I've created a validator on an XML spec that does contain GML features, but not in default FeatureCollections. Sample doc is attached, but all other docs 

I've tried several Test object types, but even with the Set of documents, the upload failes.

### Operating systems and browser
- Linux (Centos 6.9)
- Tomcat 8
- all browsers

### Steps to Reproduce

1. Go to: http://beta.validatie.geostandaarden.nl:8080/etf-webapp-2.0.0/
2. Choose validator ```StUF-Geo IMGeo versie 1.3 Geo-BOR (inclusief aanvullendeElementen)```, Run all dependencies
3. Upload the file attached with this issue

**Expected behavior:** [Which behavior you expected to see instead and why.]
An uploaded file, to start testing afterwards.

**Actual behavior:** [Describe the behavior you observed after following the steps]
Upload failed and can't start the test.

**Comment by jonherrmann** [comment]
Hi @thijsbrentjens,

this is not possible, the **Set of documents** and **Set of XML documents** test object types cannot be used anymore. This is an issue in the documentation.

I see two solutions:
- you create your own Test Object Type library based on the _etf-stdtot_ one. This also means that you need to maintain+deploy the lib on your own
- you/a contributor could reactivate the **Set of XML documents** test object type. In the first versions it was possible to use it, but it led to problems and confusion with the error messages. Therefore, we disabled it. This would require some code changes and additional unit tests

**Comment by thijsbrentjens** [comment]
O, that's a pity. 

I can imagine that if a Test Object Type (TOT) is too generic it may lead to issues. I think that a specific TOT is the best for the models we have at Geonovum. These models are GML based, but use different containers for the featurecollection. 

Correct that I only need to make changes to this class: https://github.com/etf-validator/etf-stdtot/blob/master/src/main/java/de/interactive_instruments/etf/StdTestObjectTypes.java? 

And tests?

**Comment by thijsbrentjens** [comment]
@jonherrmann just to inform you: I've created a fork and custom Test Object Types. We can use this approach, but nicer would be that we don't need changes in the sofwtware, but could do this by configuration as suggested in the ETF docs (http://docs.etf-validator.net/v2.0/Developer_manuals/Developing_Executable_Test_Suites.html#basex-test-object-types):

> In future versions of ETF it is planned that new Test Object Types may be specified by a test developer defined and declared in XML in the include-metadata directory. 

For now it works, so we can close this issue if you like.
