### ISSUE TITLE
wrong redirection when closing the Configure Test Run dialogue

### ISSUE THREAD

**Issue by MarcoMinghini** [etf-validator/etf-webapp#182]
From the ETF page http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp (or http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/#start-tests), after selecting the conformance class(es) to test and pressing _Start_, the _Configure Test Run_ dialogue opens:

![configure_test_run_dialogue](https://user-images.githubusercontent.com/14758434/48489382-383fba00-e823-11e8-9fa8-add7149d9443.png)

if the dialogue is closed (using the X button at the top left) because e.g. the user wants to change the conformance class(es) to test, the user is not redirected back to the page where the conformance class(es) can be selected/changed (http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/#start-tests), but to another page outside the ETF (http://inspire-sandbox.jrc.ec.europa.eu/#start-tests).

**Comment by jonherrmann** [comment]
Duplicate of #162

**Comment by MarcoMinghini** [comment]
Thanks. It was reported again and we opened it also in the community space ([#13](https://github.com/inspire-eu-validation/community/issues/13)). Let's continue the discussion in [#162](https://github.com/etf-validator/etf-webapp/issues/162).
