### ISSUE TITLE
ETF webapp fails to start in Internet Explorer (IE)

### ISSUE THREAD

**Issue by thijsbrentjens** [etf-validator/etf-webapp#186]
### Prerequisites for a bug report

* [x] Set a clear and descriptive title
* [x] Can you reproduce the problem
* [x] Did you [use the Github issue search](https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aetf-validator) to check whether your bug has already been reported?
* [x] Upload excerpts of the etf.log, catalina.out/log and localhost-<date>.log files. Important parts are:
the initialization log entries beginning with the ETF ASCII logo and ending with "TestRunController initialized!" plus the last exception messages. --> not relevant, a GUI thing
* [x] If the problem is related to the Web user interface: include screenshots
* [n.a.] If the problem is related to specific test data, provide the URL of your
service / the file you have uploaded or referenced.
If your service is protected or you have confidential data that you cannot
upload here, you can request an email address to which you can send URLs / files.
Please note that issues cannot be fixed for services/datasets that we cannot
access.
* [x ] Don't forget to remove sensitive information from uploaded files!!!

### Description

The ETF webapp does not start (initialize) in Internet Explorer (IE). (It does in several tested versions of Firefox and Chrome browsers)

### Operating systems and browser
- Browser: Internet Explorer (from Windows 10)

### Steps to Reproduce
1. Start Internet Explorer 
2. Open the ETF webapp, for example the INPSIRE instance: http://inspire-sandbox.jrc.ec.europa.eu/validator/

**Expected behavior:** the ETF GUI

**Actual behavior:** an error report about loading JS files.

See screenshot:

![image001](https://user-images.githubusercontent.com/1172941/51476100-c5077680-1d84-11e9-9393-4701218337d5.png)

[edit: reporting this on behalf of another user]

**Comment by jonherrmann** [comment]
Hi Thijs,

this has been fixed in version 2.0.0. See the last release notes and issue #154
