### ISSUE TITLE
Interactive progress bar

### ISSUE THREAD

**Issue by carlospzurita** [etf-validator/etf-webapp#187]
### Description

The progress bar on the Monitor Test Run dialog is interactive, the user can move it around.

### Operating systems and browser

This issue has been reproduced on Google Chrome and Mozilla Firefox on Ubuntu 18.04TLS

### Steps to Reproduce

1. Start a test run
2. Wait for the Monitor Test Run
3. Click on the progress bar and move it around

**Expected behavior:**
The progress bar should stay on the current percentage of progress
**Actual behavior:** 
The bar moves to the place it was clicked on and moves to the correct position after and advancing on the test run.

**Comment by MarcoMinghini** [comment]
The same problem occurs also on Google Chrome and Mozilla Firefox under Windows 10.

Also, there is another type of interaction that should not happen: the user is able to enter text in the text box (just below the progress bar) showing the progress of the test.

**Comment by jonherrmann** [comment]
Fixed https://github.com/etf-validator/etf-webapp/commit/7681a222442a4e54d08be6b3a157daf57d465352
