### ISSUE TITLE
Download and View Services Test Suites does not recognize services URL

### ISSUE THREAD

**Issue by carlospzurita** [etf-validator/etf-webapp#195]
### Description
There is some inconsistency in the test the services URL are subjected to, in order to detect if they are a Test Object Type supported by the selected tests. Some conformance classes work with just the host and context of the service, others need the full GetCapabilities request in order to start.

For example, in WMS, you can provide an URL without parameters (for example http://www.ign.es/wms-inspire/mapa-raster) and the test will recognize it as a valid test object type. This also works with an URL with GetCapabilities parameter.

If you try the same on WMTS, with this URL http://www.ign.es/wmts/pnoa-ma show this error message.
![Captura de pantalla de 2019-03-27 14-00-50](https://user-images.githubusercontent.com/10537778/55079525-a3847d00-509c-11e9-84eb-90e6583f621c.png)
If you provide the GetCapabilities parameters (http://www.ign.es/wmts/pnoa-ma?request=GetCapabilities&service=WMTS), it works just fine.

### Operating systems and browser
This issue happens in all browsers. Tested in Ubuntu 18.
We attach the ETF log with this issue [etf.log](https://github.com/etf-validator/etf-webapp/files/3013381/etf.log)

### Steps to Reproduce

1.Start a WMTS Test Run
2. Provide an URL with just the host and the context of the service
3. Error appears both in UI and etf.log

**Expected behavior:** 
The tests should start either with or without parameters on the URL
**Actual behavior:**
Some Test Suites accept the URL without parameters and other can't recognize the service URL.

**Comment by jonherrmann** [comment]
Hi Carlos,

when developing the test object detector, we did not take WMTS handling into account (WMS + WMTS validation were no requirement in first version). You are welcome to create a PR in the etf-stdtot repo and add the default query with the `setDefaultPathAndQuery()` method. Please see this WMS example: https://github.com/etf-validator/etf-stdtot/blob/master/src/main/java/de/interactive_instruments/etf/StdTestObjectTypes.java#L232

Cheers Jon
