### ISSUE TITLE
Error message "Could not fetch Test Objects!" appears after ETF-Validator start 

### ISSUE THREAD

**Issue by DeordD** [etf-validator/etf-webapp#212]
### Description

Directly after starting our ETF-Validator error message "Could not fetch Test Objects!" appears for few seconds. All other components of the validator are working, but test reports don't show. Instead of having all test reports shown spinner is loading all the time.

### Operating systems and browser
Operating system: Windows 7
Browser: Mozilla Firefox 60.9.0esr (64-Bit)

### Steps to Reproduce

1. Open ETF-Validator 
2. Wait for a message "Could not fetch Test Objects!" in the bottom right corner to appear
see screenshot
![grafik](https://user-images.githubusercontent.com/38787131/65312142-34429e00-db92-11e9-9445-4c298883bf4f.png)
3. When message dissapers click on Test Reports

**Expected behavior:** 
Test Reports should be shown.

**Actual behavior:**
Spinner is loading for a while and test reports are not shown.

What can I do in order to solve the problem?

Thanks in advance!

**Comment by cportele** [comment]
Since this is unusual behaviour, this issue needs to be analyzed in the context of the deployment that creates the message (and maybe the data that is used). If this occurs in the INSPIRE validator use https://github.com/inspire-eu-validation/community.

**Comment by DeordD** [comment]
Thanks a lot for the information. 

We will check the problem again in the context of the deployment.
