### ISSUE TITLE
XML validation

### ISSUE THREAD

**Issue by jonherrmann** [etf-validator/etf-webapp#85]
Cache schemas locally
- [ ] canonicalize schema files
- [ ] calculate hash
- [ ] follow imports and includes
- [ ] report broken imports or includes

Requirements:
- Performance
- Improved error messages: report broken links, etc
- Configurable (via UI) [low prio]
- Support redirects (see https://github.com/inspire-eu-validation/ets-repository/issues/121 )

[Also see](https://github.com/inspire-eu-validation/ets-repository/issues/22)

**Comment by michellutz** [comment]
We have received this message through the INSPIRE validator contact e-mail:

> Dear Support-Team,
>  
> we established a system of resolvable HTTP-UniqueRessourceIdentifiers  for data-set-metadata and use them as CoupledRessources in the service-metadata (as it is recommended/required in the TG).
> Fort that purpose we redirect the HTTP-URI to an CSW-GetRecord-Request, but unfortunately the validator shows an error (see: http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/v2/TestRuns/EIDe0228b3f-b55a-47fe-965a-a4eef48a7084.html).
>  
> The data-MD URI is: https://data.inspire.gv.at/0005/55e494dd-e0af-4806-95d6-86e30dde0504 , the URL of the service-MD is: https://geometadaten.lfrz.at/at.lfrz.discoveryservices/srv/ger/csw?service=CSW&request=GetRecordById&version=2.0.2&outputSchema=http://www.isotc211.org/2005/gmd&ElementSetName=full&id=dcb7c708-98ce-4348-9ec3-59ab0cf7d73d
>  
> Maybe this is a general problem with the correct interpretation of URL forwarding in the validator.
>  
> Can you help?

Is the reported problem covered by this issue, or should we open a dedicated issue for this?

**Comment by cportele** [comment]
Partly.

Schema validation fails as there is no xsi:schemaLocation attribute in the metadata record. If this issue would be implemented, the tests could be changed to have the XSDs pre-configured. Or the metadata publisher could fix the metadata record and add a xsi:schemaLocation attribute.

The coupled resource link raises an error as it results in a 302 response and returns text/html (but is not valid HTML as is stated in the error message). This has nothing to do with ETF, it is either something to change by the metadata publisher or requires changes to the ATS and ETS.
