### ISSUE TITLE
Add possibility to sort test reports by date, by conformance class, by category, etc. (from survey)

### ISSUE THREAD

**Issue by lorenahq** [etf-validator/etf-webapp#88]
Another idea expressed by a user would be to be able to filter the test reports by "launched by me".

The sorting could consider as well the versions of the TG if more than one is available

**Comment by jonherrmann** [comment]
> Another idea expressed by a user would be to be able to filter the test reports by "launched by me".

This would also require user management, which is not implemented in this version.

"Category" is not clear to me, as we did not use the term in ETF.

**Comment by lorenahq** [comment]
The "categories" would be the headers of the group of tests such as "Basic tests", "Data Theme", "Interoperable data sets in GML", "Metadata".

**Comment by jonherrmann** [comment]
Ah ok thanks, Lorena.

**Comment by jonherrmann** [comment]
Closing this improvement proposal in favour of https://github.com/etf-validator/governance/issues/32
