### ISSUE TITLE
More detailed help page with FAQ section (from survey)

### ISSUE THREAD

**Issue by lorenahq** [etf-validator/etf-webapp#91]

**Comment by cportele** [comment]
This is related to #71.

**Comment by jonherrmann** [comment]
An INSPIRE ETS specific FAQ section should be maintained in the INSPIRE validation community repository.

Also see the UI-related decision from the [18th SG meeting](https://github.com/etf-validator/governance/blob/master/Meetings/SG/20191217.md#governance-of-the-webapp) :

> It is agreed again that project-specific UIs should be released separately, since they do not really belong to the ETF.
