### ISSUE TITLE
Add feature to share reports by email, obtain permalink (from survey)

### ISSUE THREAD

**Issue by lorenahq** [etf-validator/etf-webapp#94]

**Comment by cportele** [comment]
The URL of the report is already included in the report, but currently only shown in the "all details" view.

**Comment by jonherrmann** [comment]
> It is agreed again that project-specific UIs should be released separately, since they do not really belong to the ETF.

see [18th SG meeting](https://github.com/etf-validator/governance/blob/master/Meetings/SG/20191217.md#governance-of-the-webapp)
