### ISSUE TITLE
Add RSS feed informing of the news items and/ or changes regarding the validator (from survey)

### ISSUE THREAD

**Issue by lorenahq** [etf-validator/etf-webapp#95]
Some of the items that could be spread through the RSS are bug fixing, availability of new conformance classes, new functionalities etc.

**Comment by jonherrmann** [comment]
> It is agreed again that project-specific UIs should be released separately, since they do not really belong to the ETF.

see [18th SG meeting](https://github.com/etf-validator/governance/blob/master/Meetings/SG/20191217.md#governance-of-the-webapp)
