### ISSUE TITLE
Shortcut to predefined groups of tests to directly test the "full compliance" of the INSPIRE resources

### ISSUE THREAD

**Issue by lorenahq** [etf-validator/etf-webapp#96]

**Comment by cportele** [comment]
This is related to #29, which has been an idea in the early design discussions. One challenge is that the current workflow would need to change and the XML files would need to be uploaded first / the XML/capabilities file at the URL would need to be downloaded first and then analysed.

**Comment by jonherrmann** [comment]
Closing this improvement proposal in favour of https://github.com/etf-validator/governance/issues/28
