### ISSUE TITLE
Simplification of the"start tests" page according to target user (from survey)

### ISSUE THREAD

**Issue by lorenahq** [etf-validator/etf-webapp#98]
A user has proposed to simplify the selection of the available tests depending on the user of the validator tool ( ITC people vs theme experts).  In particular, the proposal is "one sub-menu for Annex Data Specification tests and one for GML/Metadata/services etc."

**Comment by jonherrmann** [comment]
> It is agreed again that project-specific UIs should be released separately, since they do not really belong to the ETF.

see [18th SG meeting](https://github.com/etf-validator/governance/blob/master/Meetings/SG/20191217.md#governance-of-the-webapp)
